### ISSUE TITLE
Redirect option not work

### ISSUE THREAD

**Issue by yammycode** [bobdenotter/forms#23]
Please, help, My form config:
contact:
   notification:  

        enabled: true
        debug: false
        debug_address: my@email.com # Email address used when debug mode is enabled
        debug_smtp: false
        subject: New message
        subject_prefix: '[SITE]'
        replyto_name: '{NAME}'                 # Email addresses and names can be either the
        replyto_email: '{EMAIL}'                 # name of a field below or valid text.
        to_name: 'SITE'     
        to_email: 'my@email.com '
        from_name: 'SITE'
        from_email: 'my@email.com '
    feedback:
        success: Message submission successful
        error: There are errors in the form, please fix before trying to resubmit
        redirect:
            target: 'http://google.com'  # A page path, or URL
    fields:
        name:
            type: text
            options:
                label: false
                required: true
                attr:
                    placeholder: Your name...
                    class: uk-input uk-margin-bottom
                constraints: [ NotBlank, { Length: { 'min': 3, 'max': 128 } } ]
        email:
            type: email
            options:
                label: false
                attr:
                    placeholder: Your email...
                    class: uk-input uk-margin-bottom
                constraints: [ NotBlank, Email ]
        message:
            type: textarea
            options:
                required: true
                label: false
                attr:
                    placeholder: Your message...
                    class: uk-textarea uk-margin-bottom
        submit:
            type: submit
            options:
                label: Submit Message
                attr:
                    class: uk-button uk-button-primary uk-margin-bottom
Do I understand correctly that, in theory, there should be a redirect to google.com? But it doesn't happen.

**Comment by yammycode** [comment]
for some reason, if you do not put a line break, everything is displayed in solid text ... Notification is indented and without a blank line after, of course.

**Comment by bobdenotter** [comment]
Fixed in #56
