### ISSUE TITLE
Is the Recaptcha option implemented?

### ISSUE THREAD

**Issue by andysh-uk** [bobdenotter/forms#25]
I need to get some form of CAPTCHA on my site's contact form (which uses this extension) and whilst I can see the options are there in the config file (and I've enabled them) they don't seem to work.

Is this implemented in the Bolt 4 version of this extension, as I cannot see any code relating to it?

If it isn't, I'm happy to write this and submit a PR to implement both [reCAPTCHA](https://www.google.com/recaptcha/about/) and [hCaptcha](https://www.hcaptcha.com/) - I just wanted to confirm before I do as I didn't want to duplicate any effort.

**Comment by bobdenotter** [comment]
It's not been implemented yet, but it'd be nice to have! 

Great that you'd like to add not just recaptcha, but also hcaptcha. Privacy rocks. 👍

**Comment by andysh-uk** [comment]
Definitely and it’s always good to provide people with choices!

Leave it with me, I’ll get started in the next day or so. Can you assign this issue to me?

**Comment by I-Valchev** [comment]
Nice stuff! Assigning the issue to you, @andysh-uk !

**Comment by andysh-uk** [comment]
Just an update: this is functionally complete - implementing hCaptcha, reCAPTCHA v3, v2 checkbox and v2 invisible.

I would like to refactor my code as it’s become a little messy as the different implementations have expanded, but once I’ve done that and updated the default config with some examples, I’ll submit the PR.

**Comment by I-Valchev** [comment]
Great to hear that, @andysh-uk . Nice work.

Would it be nice to include some documentation, in the README perhaps?

**Comment by andysh-uk** [comment]
@I-Valchev Thanks!  I've just submitted the PR. I've updated the README and was planning on doing a blog post on my own site once it's live too.
