### ISSUE TITLE
Upgrade to 1.0.8 - Can't set Field 'attachments'

### ISSUE THREAD

**Issue by benr77** [bobdenotter/forms#35]
Just upgraded to 1.0.8

When I submit the form I get 

`Can't set Field 'attachments' of 'enquiries'. Make sure the Field is defined in the Enquiries ContentType.  - but I don't have a field called "attachments" in the form.`

Then if I create attachments on my content type, I resubmit again, I get 

`Can't set Field 'type_type_twitter' of 'enquiries'. Make sure the Field is defined in the Enquiries ContentType.`

I think this is the honeypot field - what config am I missing so that this does not get added to the contenttype?

Thanks

**Comment by I-Valchev** [comment]
Hi @benr77 , just noticed this myself now..

For the attachments, you can set in the `field_map` this:
```yaml
field_map:
    attachments: ~
```

For the honeypot it's tricky, because it changes name ever time... I'm not sure yet how we can solve this 🤔

**Comment by benr77** [comment]
Ok, that worked.

I have set `honeypot: false` for the moment to disable honeypot fx.

**Comment by bobdenotter** [comment]
Fixed in #69
