### ISSUE TITLE
Support for original symfony/form events

### ISSUE THREAD

**Issue by denis-gorin** [bobdenotter/forms#5]
Are you plan to support for original symfony/form events as in previous boltforms (bolt3 addon)?

If yes, I've clone and adapt this functionality from previous boltforms addon. It helped me to integrate 3d party recapture3 bundle by adding  recapture3 type on PRE_SET_DATA symfony/form event, so form starts to work like a charm

**Comment by bobdenotter** [comment]
Closed by #6 ;-)
