### ISSUE TITLE
Formatting forms

### ISSUE THREAD

**Issue by oto-emo** [bobdenotter/forms#51]
Hello,

In the Twig view, can we display the form fields individually in order to format the form?
As would be the case with form_row() functions in a standard Symfony form.

**Comment by I-Valchev** [comment]
Yes, but in that case you won't be able to use `{{ boltform('name_of_the_form') }}` to render them. Instead, use the Symfony Forms functions (`form_row()`, etc.)

**Comment by oto-emo** [comment]
Ah ok, by replacing the form view in the config yaml, I can style it. Thanks a lot. :)

**Comment by I-Valchev** [comment]
welcome :-)
