### ISSUE TITLE
reCAPTCHA form field showing as text instead of hidden

### ISSUE THREAD

**Issue by benr77** [bobdenotter/forms#57]
I'm having some trouble implementing the captcha field. With either reCAPTCHA v3 or v2 checkbox, the field is rendered as a text type, although I can see the Symfony form type extends hidden type, so looks like something is not right there.

@andysh-uk might be able to shed some light on this as he submitted the original PR.

Also, using v3 I see warnings in the JS console about the callback function not being found.

Finally, it's not clear from the README that you have to also include the recaptcha JS in a <script> tag manually - which is fine, it's just not documented and I initially expected the recaptcha module to sort this for me.

Thanks

Using latest Bolt and Bolt Forms releases

**Comment by andysh-uk** [comment]
Could it be a recurrence of [this issue](https://github.com/bolt/forms/issues/39)? 

If I remember correctly, this caused similar issues.

**Comment by benr77** [comment]
No I don't think so, there are no Javascript errors in the console.

The form field is of type text instead of hidden - surely this is generated by the backend anyway? 

Cheers

**Comment by andysh-uk** [comment]
Ah yes, it was the Honeypot that became rendered as a text field, not the captcha field, sorry.

Something doesn't sound right though - although I don't quite know what.

You shouldn't need to include the script tag for either reCAPTCHA or hCAPTCHA manually either - it gets added [here](https://github.com/bolt/forms/blob/master/templates/form.html.twig#L9) for hCAPTCHA and [here](https://github.com/bolt/forms/blob/master/templates/form.html.twig#L13) for reCAPTCHA, by the extension.

Can you post the relevant bits of your Bolt Forms config - the top-level `recaptcha` section, and the relevant field in your form's config?

**Comment by benr77** [comment]
Ok, looks like I've sorted it. I was overriding the `form.html.twig` file, but my overridden copy was from before the recaptcha stuff was added to this package, so it was missing all of the Javascript that you added. 

So now I have updated my overridden copy and all seems to be working ok.

Thanks for your help!
