### ISSUE TITLE
BCC of notification emails not being delivered

### ISSUE THREAD

**Issue by thecb1** [bobdenotter/forms#70]
> boltforms 1.4.2
> bolt 4.1.22

I don't receive notification emails to the recipient set with bcc_email while to_email and cc_email are working as expected.

No error messages, no matter if debug is on or off.

```
contact:
    notification:
        enabled: true
        debug: false
        subject: Nachricht via Kontaktformular
        subject_prefix: '[foo]'
        replyto_name: '{NAME}'                 # Email addresses and names can be either the
        replyto_email: '{EMAIL}'                 # name of a field below or valid text.
        to_name: User A
        to_email: usera@bar.com
        bcc_name: User B
        bcc_email: userb@bar.com
        [...]
```

**Comment by bobdenotter** [comment]
Seems to work for me. Have you checked the sent email in the profiler: 

![Schermafbeelding 2021-06-23 om 17 22 06](https://user-images.githubusercontent.com/1833361/123123982-8f7c8100-d447-11eb-9adc-5b80708a7c41.png)


In config: 

![Schermafbeelding_2021-06-23_om_17_20_44](https://user-images.githubusercontent.com/1833361/123123775-65c35a00-d447-11eb-8e73-5be33f1b4f51.png)


In the profiler: 

![Schermafbeelding_2021-06-23_om_17_19_19](https://user-images.githubusercontent.com/1833361/123123628-43c9d780-d447-11eb-8a9c-026766adf85e.png)

I'm receiving the `to:`, `cc:` as well as `bcc`. Why do you think its not working?

**Comment by thecb1** [comment]
Thanks for testing and posting theses screenshots!

This is weird. The profiler looks the same for me. Maybe it's the sendmail on the host I am testing this on.
I will test again with different smtp settings.

**Comment by thecb1** [comment]
Maybe related: https://github.com/symfony/symfony/pull/39744

**Comment by thecb1** [comment]
Using sendmail://default instead of native://default as mentioned in https://github.com/symfony/symfony/issues/40070 fixed it for me. Thanks again :)

**Comment by bobdenotter** [comment]
Ok, glad it works! 👍
