### ISSUE TITLE
Honeypot not blocking/marking mails

### ISSUE THREAD

**Issue by thecb1** [bobdenotter/forms#71]
Both `spam-action` settings for the honeypot are not preventing spam from being processed.

Details
-------

> Bolt 4.1.22 composer install
> PHP 7.3
> Boltforms 1.4.2
```
csrf: true
honeypot: true
spam-action: one of ['mark-as-spam', 'block']
```
### Steps to reproduce

Fill out form with email notification and enter some text in the hidden honeypot input then submit.

### Expected result

Subject of email notification gets '[SPAM] ' prepended.

### Actual result

Email notification delivered without spam prefix in the subject.

### Steps to reproduce

Fill out form with email notification and enter some text in the hidden honeypot input then submit.

### Expected result

`An extra special error occured.`  is shown and email is not being sent.

### Actual result

`An extra special error occured.` is shown additionally to what is set in `feedback: error:` and the email notification is still sent.

**Comment by bobdenotter** [comment]
Fix is in the pipeline: #72
