### ISSUE TITLE
Query in feedback.redirect option doesn't work

### ISSUE THREAD

**Issue by Virprince** [bobdenotter/forms#74]
in config.yaml we can see the feedback option

```
#    feedback:
#        success: Form submission sucessful
#        error: There are errors in the form, please fix before trying to resubmit
#        redirect:
#            target: page/another-page  # A page path, or URL
#            query: [ name, email ]     # Optional keys for the GET parameters
```

The redirect.target option works perfectly but the query option seems to be ignored in code. 
No sign of ['query'] in src/EventSubscriber/Redirect and in entire extension files.

**Comment by bobdenotter** [comment]
Pull request is in the queue: #76
